'''
Created on Mar 18, 2021

@author: andrei
'''

# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


class BookGymSpot():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.driver.get("https://www.laurierathletics.com/ecommerce/user/index.php")
    self.vars = {}
    
    
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test1(self, login, password, dateThreeDaysFromNow, desired_time, bookingType):
      
    columnList = []
#     self.driver.get("https://www.laurierathletics.com/ecommerce/user/index.php")
    self.driver.find_element(By.NAME, "UserLogin").click()
    self.driver.find_element(By.NAME, "UserLogin").send_keys(login)
    self.driver.find_element(By.NAME, "Password").send_keys(password)
    self.driver.find_element(By.NAME, "submit_Login").click()
    self.driver.find_element(By.LINK_TEXT, "2").click()
    trs = self.driver.find_elements(By.TAG_NAME, "tr") 
    
    for row in trs:
        tds = row.find_elements(By.TAG_NAME, "td")
        
        for column in tds:
            columnList.append(column.text)
#         print(columnList)
        
        
        conditionType = False
        conditionDate = False
        conditionTime = False
        conditionReservations = False
        
        if len(columnList) == 8:
        
            if columnList[2] == bookingType:
                conditionType = True
            if columnList[3] == dateThreeDaysFromNow:
                conditionDate = True
            if columnList[4] == desired_time:
                conditionTime = True
            if columnList[7] != "Reservation Not Available.":
                conditionReservations = True
            
        # If spot is able to be booked
        if(conditionType and conditionDate and conditionReservations and conditionTime):
            try:
                tds[7].click()
                self.driver.find_element(By.NAME, "waiver1").click()
                dropdown = self.driver.find_element(By.NAME, "waiver1")
                dropdown.find_element(By.XPATH, "//option[. = 'I Agree to the terms above']").click()
                self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(9) > option:nth-child(2)").click()
                self.driver.find_element(By.NAME, "waiver2").click()
                dropdown = self.driver.find_element(By.NAME, "waiver2")
                dropdown.find_element(By.XPATH, "//option[. = 'I Agree to the terms above']").click()
                self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(27) > option:nth-child(2)").click()
                self.driver.find_element(By.NAME, "makereservation").click()
                print("Spot booked: " + columnList[2] + " on " + columnList[3] + " at " + columnList[4])
            except:
                print("Booking failed.")
            
            
            
            break
        
        columnList = []